#!/bin/bash

### comicarchive Usage:help
#
#	comicarchive { cbz | pdf } COMICFOLDER
#	make_archive:main { cbz | pdf } COMICFOLDER
#
# When run as standalone, the comicarchive command/subroutine turns a folder of
#
# 	chapter_X/page_*
#
# into a single chapter_X.pdf or chapter_X.cbz
#
# Set NOREMOVE=true to prevent removeal of original files
#
# Set NOERMOVE=false to remove files after archive is made
#
###/doc

#%include bincheck.sh out.sh abspath.sh runmain.sh

make_archive:remove() {
	local targetdir="$1"; shift
	[[ "${NOREMOVE:-}" = true ]] || { cd ..; rm -r "$targetdir" ; }
}

make_archive:pdf() {
	local targetdir="$(abspath:path "$1")"; shift
	local archivename="$targetdir.pdf"

	if bincheck:has img2pdf; then
		(
		cd "$targetdir/"
		img2pdf -o "$archivename" page_* && {
			cd ..
			make_archive:remove "$targetdir"
		}
		)
	else
		out:warn "'img2pdf' command not installed"
	fi
}

make_archive:cbz() {
	local targetdir="$(abspath:path "$1")"; shift
	local archivename="$targetdir.cbz"

	if bincheck:has zip; then
		(
		# Comic book archives need a special comic book reader
		#  but they are recognized by eBook readers, and can be unpacked
		#  since they're literally a ZIP file
		#  and displayed in name order
		cd "$targetdir/"
		zip "$archivename" $(echo page_*) && {
			cd ..
			make_archive:remove "$targetdir"
		}
		)
	else
		out:warn "'zip' command not installed"
	fi
}

make_archive:main() {
	local archivetype="$1"; shift
	local targetdir="$1"; shift

	case "$archivetype" in
	pdf)
		make_archive:pdf "$targetdir"
		;;
	cbz)
		make_archive:cbz "$targetdir"
		;;
	*)
		out:fail "Wrong archive type name [$archivetype] - choose 'cbz' or 'pdf'"
		;;
	esac
}

if [[ -z "${NOREMOVE:-}" ]]; then
	NOREMOVE=false
fi

runmain comicarchive make_archive:main "$@"
