#!/bin/bash

### mfcom Usage:help
#
# MangaFox Compiler
#
# Get all pages from a MangaFox commic to a local directory
#
# USAGE
#
# 	mfcom URL [ START [END] ]
#
# Specify the URL of the main manga page
#
# Optionally specify the start chapter
#
# Optionally specify the end chapter
#
###/doc

set -euo pipefail

#%include version.sh notest.sh
#%include bashout.sh autohelp.sh varify.sh

function wgetdl {
	local downloadfile="$1"; shift
	wget --header="$UAGENT" --header="Accept: text/html, image/*" --quiet -O "$downloadfile" "$@"
	do_unzip "$downloadfile"
}

function get_mainList {
	wgetdl "$F_MAIN" "$U_MAINPAGE"
}

function extract_links {
	local sourcefile="$1"; shift
	local targetfile="$1"; shift

	grep "$U_MAINPAGE" "$sourcefile" | grep -Po 'a href="'"$U_MAINPAGE"'.*?"'|grep -Po "$U_MAINPAGE[^\"]+" > "$targetfile"
}

function do_unzip {
	if (file "$1"|grep gzip -q); then
		mv "$1" "$1.gz"
		gunzip "$1.gz"
	fi
}

function padnum {
	printf %03d "$1"
}

function set_image_extension {
	local imagefile="$1"; shift
	local imagetype="$(file "$imagefile"|egrep -oi 'jpeg|jpg|png|gif' | tr '[:upper:]' '[:lower:]')"
	local extension=bin

	infoe "Renaming $imagefile"

	case "$imagetype" in
		jpeg|jpg)
			extension=jpg ;;
		png)
			extension=png ;;
		gif)
			extension=gif ;;
		*)
			warne "Could not determine extension for $1"
			return ;;
	esac

	mv "$imagefile" "$imagefile.$extension"

}

function download_chapter_page {
	local pageurl="$1"; shift
	local targetfile="$1"; shift

	wgetdl "$targetfile" "$pageurl"

	local imgurl="$(grep '<img' "$targetfile"|grep 'id="image"'|grep -oP 'src="[^"]+')"

	debuge "Cutting $imgurl"

	imgurl="${imgurl:5}"

	debuge "$imgurl : $targetfile"
	wgetdl "$targetfile" "$imgurl"
	set_image_extension "$targetfile"

}

function download_chapter {
	local chapter_url="$1"; shift
	local base_url="$(dirname "$chapter_url")"
	local targetdir="$1"; shift
	local dlfile="$targetdir/fpage.html"

	mkdir -p "$targetdir"

	wgetdl "$dlfile" "$chapter_url"

	local pagecount="$(grep -oP 'of\s*\d+' "$dlfile"|sort|uniq|cut -d' ' -f2)"

	local i=0
	while [[ "$i" -lt "$pagecount" ]]; do
		i=$((i+1))
		download_chapter_page "$base_url/$i.html" "$targetdir/page_$(padnum "$i")"
	done
}

function download_all_chapters {
	local i=0
	while read LINKLINE; do
		i=$((i+1))

		if [[ -n  "$STARTINDEX" ]]; then
			if [[ ! "$i" -ge "$STARTINDEX" ]]; then continue; fi

			if [[ -n "$ENDINDEX" ]]; then
				if [[ ! "$i" -le "$ENDINDEX" ]]; then continue; fi
			fi
		fi
		
		download_chapter "$LINKLINE" "$D_TARGET/chapter_$(padnum "$i")"

	done < <(tac "$F_LINKS")
}

function numcheck {
	local tocheck="$1"; shift

	if [[ ! "$tocheck" =~ ^[0-9]*$ ]]; then
		faile Invalid "$*"
	fi
}

function main {
	if [[ -z "$*" ]]; then
		printhelp
		exit
	fi

	UAGENT="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

	U_MAINPAGE="$1"; shift

	STARTINDEX="${1:-}"
	ENDINDEX="${2:-}"

	numcheck "$STARTINDEX" start index
	numcheck "$ENDINDEX" end index

	H_MANGA="$(echo "$U_MAINPAGE"|md5sum)"
	H_MANGA="${H_MANGA:0:6}"
	D_TARGET="$(varify_fil "$H_MANGA-$U_MAINPAGE")"
	F_MAIN="$D_TARGET/frontpage.html"
	F_LINKS="$D_TARGET/links.txt"

	mkdir -p "$D_TARGET"

	get_mainList
	extract_links "$F_MAIN" "$F_LINKS"
	download_all_chapters
}

notest main "$@"

#for i in 1 2 3 4 5 ; do (n=005; cd chapter_; pwd; img2pdf -o 15sai_.pdf *.jpg); done
#mv */*.pdf ./
#rm chapter_* -r frontpage.html links.txt 
