#!/bin/bash

### mfcom Usage:help
#
# MangaFox Compiler
#
# Get all pages from a MangaFox commic to a local directory
#
# USAGE
#
# 	mfcom URL [ START [END] ]
#
# Specify the URL of the main manga page
#
# Optionally specify the start chapter
#
# Optionally specify the end chapter
#
# CONFIGURATION
#
# Set the following environment variables to configure mfcom:
#
# MFCOM_UAGENT="<user agent string>"
# 	set a custom user agent string instead of the default (Mozilla 52)
#
# MFCOM_MAKE_ARCHIVE={pdf | cbz}
# 	tries to compile to PDF or CBZ comic archive
#
# 	PDF requires img2pdf
# 	CBZ requires zip
#
# MFCOM_WAIT=<int>
# 	time in seconds to wait between operations ; default is 1
# 	mangafox seems to throttle access from IPs that download too much too fast
# 	set to 0 for no delay
#
###/doc

set -euo pipefail

#%include version.sh notest.sh
#%include bashout.sh autohelp.sh varify.sh getbin.sh
#%include comicarchive

function wgetdl {
	local downloadfile="$1"; shift
	if [[ -z "$*" ]]; then
		warne "Error downloading $downloadfile"
		return 404
	fi

	wget --header="User-Agent: $MFCOM_UAGENT" --header="Accept: text/html, image/*" --quiet -O "$downloadfile" --no-check-certificate "$@" || :
	do_unzip "$downloadfile"
}

function get_mainList {
	wgetdl "$F_MAIN" "$U_MAINPAGE"
}

function extract_links {
	local sourcefile="$1"; shift
	local targetfile="$1"; shift

	grep "$U_MAINPAGE_NOSCHEME" "$sourcefile" | \
		grep -Po 'a href="'"$U_MAINPAGE_NOSCHEME"'.*?"' | \
		grep -Po "$U_MAINPAGE_NOSCHEME[^\"]+" | \
		sed -r 's|^|http:|' | tac \
		> "$targetfile"
}

function unzero() {
	echo "$1"|sed -r s/^0+//
}

function isbigger() {
	local bigger="$(unzero "$1")"; shift
	local smaller="$(unzero "$1")"; shift

	python -c "if $bigger <= $smaller: exit(1)"
}

function do_unzip {
	if (file "$1"|grep gzip -q); then
		mv "$1" "$1.gz"
		gunzip "$1.gz"
	fi
}

function set_image_extension {
	local imagefile="$1"; shift
	local imagetype="$(file "$imagefile"|egrep -oi 'jpeg|jpg|png|gif' | tr '[:upper:]' '[:lower:]')"
	local extension=bin

	infoe "Renaming $imagefile"

	case "$imagetype" in
		jpeg|jpg)
			extension=jpg ;;
		png)
			extension=png ;;
		gif)
			extension=gif ;;
		*)
			warne "Could not determine extension for $imagefile"
			return ;;
	esac

	mv "$imagefile" "$imagefile.$extension"

	lastextension="$extension"
}

function download_chapter_page {
	local pageurl="$1"; shift
	local targetfile="$1"; shift

	wgetdl "$targetfile" "$pageurl"
	[[ "$?" = 404 ]] && return 404

	local imgurl="$(grep '<img' "$targetfile"|grep 'id="image"'|grep -oP 'src="[^"]+')"

	debuge "Cutting $imgurl"

	imgurl="${imgurl:5}"

	debuge "$imgurl : $targetfile"
	wgetdl "$targetfile" "$imgurl"
	[[ "$?" = 404 ]] && return 404
	set_image_extension "$targetfile"
}

padnum() {
	printf "%03d" "$1"
}

function download_chapter {
	local chapter_url="$1"; shift
	local base_url="$(dirname "$chapter_url")"
	local targetdir="$1"; shift
	local dlfile="$targetdir/fpage.html"
	local chapdir="$(basename "$targetdir")"

	mkdir -p "$targetdir"

	wgetdl "$dlfile" "$chapter_url"

	local pagecount="$(grep -oP 'of\s*\d+' "$dlfile"|sort|uniq|cut -d' ' -f2)"

	local i=0
	while [[ "$i" -lt "$pagecount" ]]; do
		i=$((i+1))
		download_chapter_page "$base_url/$i.html" "$targetdir/page_$(padnum "$i")"
		sleep "$MFCOM_WAIT"
	done

	local archivename="$(varify_fil "$chapdir")"
	if [[ "${MFCOM_MAKE_ARCHIVE:-}" = pdf ]]; then
		make_archive:pdf "$targetdir"
	elif [[ "${MFCOM_MAKE_ARCHIVE:-}" = cbz ]]; then
		make_archive:cbz "$targetdir"
	fi
}

function download_all_chapters {
	local i=0
	while read LINKLINE; do
		chappat="/c([0-9.]+)/?"
		[[ "$LINKLINE" =~ $chappat ]]
		i="${BASH_REMATCH[1]}"
		if [[ -z "$i" ]]; then
			warne "Could not extract chapter number from $LINKLINE"
			continue
		fi

		if [[ -n  "$STARTINDEX" ]]; then
			if isbigger "$STARTINDEX" "$i"; then continue; fi

			if [[ -n "$ENDINDEX" ]]; then
				if ! isbigger "$ENDINDEX" "$i" ; then break; fi
			fi
		fi
		
		download_chapter "$LINKLINE" "$D_TARGET/chapter_${i}"

	done < "$F_LINKS"
}

function numcheck {
	local tocheck="$1"; shift

	if [[ ! "$tocheck" =~ ^[0-9]*$ ]]; then
		faile Invalid "$*"
	fi
}

function main {
	if [[ -z "$*" ]]; then
		printhelp
		exit
	fi

	: ${MFCOM_UAGENT="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"}

	: ${MFCOM_WAIT=2}

	U_MAINPAGE="$1"; shift
	# Mangafox has started generating urls without schemes
	U_MAINPAGE_NOSCHEME="$(echo "$U_MAINPAGE"|sed -r 's|https?://|//|')"

	STARTINDEX="${1:-}"
	ENDINDEX="${2:-}"

	numcheck "$STARTINDEX" start index
	numcheck "$ENDINDEX" end index

	D_TARGET="$(varify_fil "${U_MAINPAGE##*mangafox.me/manga/}")"
	D_TARGET="${D_TARGET%_}"
	F_MAIN="$D_TARGET/frontpage.html"
	F_LINKS="$D_TARGET/links.txt"

	# =====================
	echo "MFCOM_WAIT=$MFCOM_WAIT"
	echo "MFCOM_MAKE_ARCHIVE=${MFCOM_MAKE_ARCHIVE:-}"
	echo "Downloading to: $D_TARGET"
	sleep 2

	mkdir -p "$D_TARGET"

	get_mainList
	extract_links "$F_MAIN" "$F_LINKS"
	download_all_chapters
}

notest main "$@"

